code --install-extension alefragnani.bookmarks
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension github.vscode-github-actions
code --install-extension jock.svg
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.remote-explorer
code --install-extension oderwat.indent-rainbow
code --install-extension takumii.markdowntable
code --install-extension usernamehw.errorlens
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
