code --install-extension aaron-bond.better-comments
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension drKnoxy.eslint-disable-snippets
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension jasonnutter.search-node-modules
code --install-extension jock.svg
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension mutantdino.resourcemonitor
code --install-extension PKief.material-icon-theme
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension styled-components.vscode-styled-components
code --install-extension usernamehw.errorlens
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
